import type {
  Product,
  Warehouse,
  StockMovement,
  Category,
  Supplier,
  Employee,
  AuditLog,
  Notification,
  DashboardStats,
  InventoryItem,
  StockRequest,
} from "@/types"

export const mockProducts: Product[] = [
  {
    id: "1",
    sku: "PROD-001",
    name: "Industrial Steel Bearing",
    barcode: "8901234567890",
    category: "Bearings",
    supplier: "1",
    unit: "pieces",
    currentStock: 450,
    reservedStock: 50,
    minStock: 100,
    maxStock: 500,
    price: 25.5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    sku: "PROD-002",
    name: "Hydraulic Pump Assembly",
    barcode: "8901234567891",
    category: "Pumps",
    supplier: "2",
    unit: "pieces",
    currentStock: 120,
    reservedStock: 30,
    minStock: 50,
    maxStock: 200,
    price: 425.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    sku: "PROD-003",
    name: "Stainless Steel Fastener Kit",
    barcode: "8901234567892",
    category: "Fasteners",
    supplier: "1",
    unit: "boxes",
    currentStock: 890,
    reservedStock: 100,
    minStock: 200,
    maxStock: 1000,
    price: 15.25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    sku: "PROD-004",
    name: "Industrial Motor Controller",
    barcode: "8901234567893",
    category: "Electronics",
    supplier: "3",
    unit: "pieces",
    currentStock: 45,
    reservedStock: 10,
    minStock: 25,
    maxStock: 100,
    price: 850.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    sku: "PROD-005",
    name: "Conveyor Belt Segment",
    barcode: "8901234567894",
    category: "Conveyor Systems",
    supplier: "2",
    unit: "meters",
    currentStock: 250,
    reservedStock: 40,
    minStock: 75,
    maxStock: 300,
    price: 125.5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockWarehouses: Warehouse[] = [
  {
    id: "1",
    name: "Main Warehouse",
    code: "WH-001",
    address: "123 Industrial Ave",
    city: "New York",
    country: "USA",
    capacity: 10000,
    currentLoad: 7250,
    manager: "John Manager",
    zones: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Distribution Center",
    code: "WH-002",
    address: "456 Logistics Blvd",
    city: "Los Angeles",
    country: "USA",
    capacity: 8000,
    currentLoad: 5600,
    manager: "Sarah Manager",
    zones: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockCategories: Category[] = [
  { id: "1", name: "Bearings", createdAt: new Date().toISOString() },
  { id: "2", name: "Pumps", createdAt: new Date().toISOString() },
  { id: "3", name: "Fasteners", createdAt: new Date().toISOString() },
  { id: "4", name: "Electronics", createdAt: new Date().toISOString() },
  { id: "5", name: "Conveyor Systems", createdAt: new Date().toISOString() },
  { id: "6", name: "Motors", createdAt: new Date().toISOString() },
  { id: "7", name: "Valves", createdAt: new Date().toISOString() },
]

export const mockSuppliers: Supplier[] = [
  {
    id: "1",
    name: "Global Industrial Supplies",
    email: "contact@globalind.com",
    phone: "+1-555-0100",
    address: "789 Supply St",
    city: "Houston",
    country: "USA",
    contactPerson: "Michael Chen",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Technical Components Ltd",
    email: "sales@techcomp.com",
    phone: "+1-555-0101",
    address: "321 Tech Park",
    city: "San Francisco",
    country: "USA",
    contactPerson: "Emma Wilson",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Premium Electronics Co",
    email: "info@premiumelec.com",
    phone: "+1-555-0102",
    address: "654 Electronics Ln",
    city: "Boston",
    country: "USA",
    contactPerson: "David Kumar",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockEmployees: Employee[] = [
  {
    id: "1",
    userId: "1",
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@company.com",
    phone: "+1-555-0110",
    department: "Warehouse",
    position: "Warehouse Manager",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    userId: "2",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@company.com",
    phone: "+1-555-0111",
    department: "Inventory",
    position: "Inventory Specialist",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockStockMovements: StockMovement[] = [
  {
    id: "1",
    productId: "1",
    fromLocation: "Warehouse A",
    toLocation: "Warehouse B",
    quantity: 50,
    reason: "Transfer Between Warehouses",
    user: "John Smith",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    productId: "2",
    fromLocation: "Stock",
    toLocation: "Production",
    quantity: 30,
    reason: "Production Consumption",
    user: "Sarah Johnson",
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockAuditLogs: AuditLog[] = [
  {
    id: "1",
    user: "John Smith",
    action: "CREATE",
    entity: "Product",
    entityId: "1",
    changes: { name: "Industrial Steel Bearing", sku: "PROD-001" },
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    user: "Sarah Johnson",
    action: "UPDATE",
    entity: "Product",
    entityId: "2",
    changes: { currentStock: 120 },
    createdAt: new Date().toISOString(),
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "1",
    userId: "1",
    title: "Low Stock Alert",
    message: "Product PROD-004 is below minimum stock level",
    type: "alert",
    read: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    userId: "1",
    title: "Stock Request Approved",
    message: "Your stock request for PROD-001 has been approved",
    type: "approval",
    read: true,
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
]

export const mockDashboardStats: DashboardStats = {
  totalProducts: 156,
  inventoryValue: 487250.5,
  criticalStockItems: 8,
  pendingRequests: 12,
  activeEmployees: 24,
  totalWarehouses: 2,
}

export const mockStockRequests: StockRequest[] = [
  {
    id: "1",
    productId: "1",
    quantity: 100,
    reason: "adjustment",
    status: "pending",
    requester: "John Smith",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    productId: "2",
    quantity: 50,
    reason: "transfer",
    fromWarehouse: "WH-001",
    toWarehouse: "WH-002",
    status: "approved",
    requester: "Sarah Johnson",
    approver: "Manager Name",
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockInventoryItems: InventoryItem[] = [
  {
    id: "1",
    productId: "1",
    warehouseId: "1",
    locationId: "WH1-Z1-R1-S1",
    quantity: 450,
    reservedQuantity: 50,
    lastChecked: new Date().toISOString(),
  },
  {
    id: "2",
    productId: "2",
    warehouseId: "1",
    locationId: "WH1-Z2-R2-S1",
    quantity: 120,
    reservedQuantity: 30,
    lastChecked: new Date().toISOString(),
  },
]
